version: '3.0'

services:
  grafana:
    container_name: 'knightss27-weathermap-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-11.1.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/knightss27-weathermap-panel
      - ./provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
