version: '3.7'

services:
  grafana:
    build:
      context: grafana
      dockerfile: Dockerfile
      args:
        GRAFANA_VERSION: 8.1.8
        GF_INSTALL_PLUGINS: https://github.com/knightss27/grafana-network-weathermap/releases/download/v0.0.9/grafana-weathermap-plugin-v0.0.9.zip;network-weathermap
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus
    volumes:
      - .\exporter\prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  exporter:
    build:
      context: exporter
      dockerfile: Dockerfile
