version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3101:3000
    volumes:
      - ~/grafana-plugins:/var/lib/grafana/plugins
    environment:
      - GF_APP_MODE=development
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=knightss27-weathermap-panel
  prometheus:
    image: prom/prometheus
    volumes:
      - ./exporter/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  exporter:
    build:
      context: exporter
      dockerfile: Dockerfile
