site_name: Grafana Network Weathermap Plugin
repo_url: https://github.com/knightss27/grafana-network-weathermap
theme:
  name: material
  features:
    - navigation.sections
  logo: assets/logo.svg
  palette:
    primary: black 
