name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run build
      - name: Create zip archive
        run: zip grafana-weathermap-plugin-$(git describe --tags `git rev-list --tags --max-count=1`).zip dist -r
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: grafana-weathermap-plugin*.zip
